/**
 * @description       : 
 * @author            : Brian Ezell (Simply EZ)
 * @group             : 
 * @last modified on  : 07-28-2025
 * @last modified by  : Brian Ezell (Simply EZ)
**/

public with sharing class CaseTriggerController {

    /**
    * @description Update progress on child and parent cases when
    *   a task is completed or uncompleted
    * @author Brian Ezell (Simply EZ)
    * @param newCases
    * @param oldMap
    * @return void
    **/
 

}